<a href="https://colab.research.google.com/github/JaimeBaez71/Modelos-de-Regresi-n-Lineal/blob/main/Modelos_de_Regresion_lineal.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [27]:
#importamos librerias
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
#Cargar archivo csv desde equipo
from google.colab import files
files.upload()

In [ ]:
df1= pd.read_csv("cuentas_credicel.csv", encoding= 'latin')
pd.options.display.max_columns = None
df1.head(50)

In [63]:
df=df1.copy()

In [64]:
#Sustituimos valores nulos y strings y cambiamos los valores de Object a int
df["riesgo"]=df["riesgo"].str.replace("Cancelado","0")
df["riesgo"]=df["riesgo"].str.replace("Fraude","0")
df["riesgo"]=df["riesgo"].str.replace("Atraso","0")
df["riesgo"]= df["riesgo"].fillna(0)

df["plazo"]=df["plazo"].str.replace("S","")
df['plazo']= df['plazo'].astype(int)

df["porc_enganche"]= df["porc_enganche"].fillna(round(df1["porc_enganche"].mean(),1))

In [ ]:
df.head(50)

In [ ]:
#Corrobaromas valores nulos en todo el dataframe
valores_nulos=df.isnull().sum()
valores_nulos

**Modelo Matematico 1**

In [42]:
#Declaramos las variables dependientes e independientes para la regresión lineal
Vars_Indep= df[['porc_tasa']]
Var_Dep= df['enganche']
#Se define model como la función de regresión lineal
from sklearn.linear_model import LinearRegression
model= LinearRegression()
#Ajustamos el modelo con las variables antes declaradas
model.fit(X=Vars_Indep, y=Var_Dep)
#Verificamos los coeficientes obtenidos para el modelo ajustado
model.__dict__

{'fit_intercept': True,
 'copy_X': True,
 'n_jobs': None,
 'positive': False,
 'feature_names_in_': array(['porc_tasa'], dtype=object),
 'n_features_in_': 1,
 'coef_': array([-1.58267294]),
 'rank_': 1,
 'singular_': array([1161.91123173]),
 'intercept_': 928.8307344701436}

y=-1.58267294+928.8307344701436

In [43]:
#Predecimos los valores de total de accidentes a partir de la variable
y_pred= model.predict(X=df[["porc_tasa"]])
y_pred

array([928.83073447, 928.83073447, 928.83073447, ..., 927.64372977,
       929.05230868, 933.38883253])

In [44]:
#Corroboramos cual es el coeficiente de Determinación de nuestro modelo
coef_Deter=model.score(X=Vars_Indep, y=Var_Dep)
coef_Deter

0.0006546161532061667

**Modelo Matematico 2**

In [45]:
#Declaramos las variables dependientes e independientes para la regresión lineal
Vars_Indep= df[['porc_tasa']]
Var_Dep= df['precio']
#Se define model como la función de regresión lineal
from sklearn.linear_model import LinearRegression
model= LinearRegression()
#Ajustamos el modelo con las variables antes declaradas
model.fit(X=Vars_Indep, y=Var_Dep)
#Verificamos los coeficientes obtenidos para el modelo ajustado
model.__dict__

{'fit_intercept': True,
 'copy_X': True,
 'n_jobs': None,
 'positive': False,
 'feature_names_in_': array(['porc_tasa'], dtype=object),
 'n_features_in_': 1,
 'coef_': array([-6.73481928]),
 'rank_': 1,
 'singular_': array([1161.91123173]),
 'intercept_': 4007.2210996335884}

y=-6.73481928+4007.2210996335884

In [46]:
#Predecimos los valores de total de accidentes a partir de la variable
y_pred= model.predict(X=df[["porc_tasa"]])
y_pred

array([4007.22109963, 4007.22109963, 4007.22109963, ..., 4002.16998517,
       4008.16397433, 4026.61737916])

In [47]:
#Corroboramos cual es el coeficiente de Determinación de nuestro modelo
coef_Deter=model.score(X=Vars_Indep, y=Var_Dep)
coef_Deter

0.001453055074519316

**Modelo Matematico 3**

In [48]:
#Declaramos las variables dependientes e independientes para la regresión lineal
Vars_Indep= df[['porc_tasa']]
Var_Dep= df['costo_total']
#Se define model como la función de regresión lineal
from sklearn.linear_model import LinearRegression
model= LinearRegression()
#Ajustamos el modelo con las variables antes declaradas
model.fit(X=Vars_Indep, y=Var_Dep)
#Verificamos los coeficientes obtenidos para el modelo ajustado
model.__dict__

{'fit_intercept': True,
 'copy_X': True,
 'n_jobs': None,
 'positive': False,
 'feature_names_in_': array(['porc_tasa'], dtype=object),
 'n_features_in_': 1,
 'coef_': array([-29.81472897]),
 'rank_': 1,
 'singular_': array([1161.91123173]),
 'intercept_': 5744.778665802484}

y=-29.81472897+5744.778665802484

In [49]:
#Predecimos los valores de total de accidentes a partir de la variable
y_pred= model.predict(X=df[["porc_tasa"]])
y_pred

array([5744.7786658 , 5744.7786658 , 5744.7786658 , ..., 5722.41761907,
       5748.95272786, 5830.64508525])

In [50]:
#Corroboramos cual es el coeficiente de Determinación de nuestro modelo
coef_Deter=model.score(X=Vars_Indep, y=Var_Dep)
coef_Deter

0.009272642721947721

**Modelo Matematico 4**

In [51]:
#Declaramos las variables dependientes e independientes para la regresión lineal
Vars_Indep= df[['porc_tasa']]
Var_Dep= df['pagos_realizados']
#Se define model como la función de regresión lineal
from sklearn.linear_model import LinearRegression
model= LinearRegression()
#Ajustamos el modelo con las variables antes declaradas
model.fit(X=Vars_Indep, y=Var_Dep)
#Verificamos los coeficientes obtenidos para el modelo ajustado
model.__dict__

{'fit_intercept': True,
 'copy_X': True,
 'n_jobs': None,
 'positive': False,
 'feature_names_in_': array(['porc_tasa'], dtype=object),
 'n_features_in_': 1,
 'coef_': array([0.03074397]),
 'rank_': 1,
 'singular_': array([1161.91123173]),
 'intercept_': 10.134286976970543}

y=0.03074397+10.134286976970543

In [52]:
#Predecimos los valores de total de accidentes a partir de la variable
y_pred= model.predict(X=df[["porc_tasa"]])
y_pred

array([10.13428698, 10.13428698, 10.13428698, ..., 10.15734496,
       10.12998282, 10.04574434])

In [54]:
#Corroboramos cual es el coeficiente de Determinación de nuestro modelo
coef_Deter=model.score(X=Vars_Indep, y=Var_Dep)
coef_Deter

0.0005955114161472208

**Modelo Matematico 5**

In [67]:
#Declaramos las variables dependientes e independientes para la regresión lineal
Vars_Indep= df[['porc_tasa']]
Var_Dep= df['riesgo']
#Se define model como la función de regresión lineal
from sklearn.linear_model import LinearRegression
model= LinearRegression()
#Ajustamos el modelo con las variables antes declaradas
model.fit(X=Vars_Indep, y=Var_Dep)
#Verificamos los coeficientes obtenidos para el modelo ajustado
model.__dict__

{'fit_intercept': True,
 'copy_X': True,
 'n_jobs': None,
 'positive': False,
 'feature_names_in_': array(['porc_tasa'], dtype=object),
 'n_features_in_': 1,
 'coef_': array([-0.05087199]),
 'rank_': 1,
 'singular_': array([1161.91123173]),
 'intercept_': 2.231017904804726}

y=-0.05087199+2.231017904804726

In [68]:
#Predecimos los valores de total de accidentes a partir de la variable
y_pred= model.predict(X=df[["porc_tasa"]])
y_pred

array([2.2310179 , 2.2310179 , 2.2310179 , ..., 2.19286391, 2.23813998,
       2.37752925])

In [69]:
#Corroboramos cual es el coeficiente de Determinación de nuestro modelo
coef_Deter=model.score(X=Vars_Indep, y=Var_Dep)
coef_Deter

0.0007944945907698564

**Modelo Matematico 6**

In [70]:
#Declaramos las variables dependientes e independientes para la regresión lineal
Vars_Indep= df[['porc_tasa']]
Var_Dep= df['plazo']
#Se define model como la función de regresión lineal
from sklearn.linear_model import LinearRegression
model= LinearRegression()
#Ajustamos el modelo con las variables antes declaradas
model.fit(X=Vars_Indep, y=Var_Dep)
#Verificamos los coeficientes obtenidos para el modelo ajustado
model.__dict__

{'fit_intercept': True,
 'copy_X': True,
 'n_jobs': None,
 'positive': False,
 'feature_names_in_': array(['porc_tasa'], dtype=object),
 'n_features_in_': 1,
 'coef_': array([-0.24476901]),
 'rank_': 1,
 'singular_': array([1161.91123173]),
 'intercept_': 26.279798588221073}

y=-0.24476901+26.279798588221073

In [71]:
#Predecimos los valores de total de accidentes a partir de la variable
y_pred= model.predict(X=df[["porc_tasa"]])
y_pred

array([26.27979859, 26.27979859, 26.27979859, ..., 26.09622183,
       26.31406625, 26.98473334])

In [72]:
#Corroboramos cual es el coeficiente de Determinación de nuestro modelo
coef_Deter=model.score(X=Vars_Indep, y=Var_Dep)
coef_Deter

0.03566074083655013

**Modelo Matematico 7**

In [73]:
#Declaramos las variables dependientes e independientes para la regresión lineal
Vars_Indep= df[['porc_tasa']]
Var_Dep= df['monto_financiado']
#Se define model como la función de regresión lineal
from sklearn.linear_model import LinearRegression
model= LinearRegression()
#Ajustamos el modelo con las variables antes declaradas
model.fit(X=Vars_Indep, y=Var_Dep)
#Verificamos los coeficientes obtenidos para el modelo ajustado
model.__dict__

{'fit_intercept': True,
 'copy_X': True,
 'n_jobs': None,
 'positive': False,
 'feature_names_in_': array(['porc_tasa'], dtype=object),
 'n_features_in_': 1,
 'coef_': array([-5.3397735]),
 'rank_': 1,
 'singular_': array([1161.91123173]),
 'intercept_': 3084.211509627098}

y=-5.3397735+3084.211509627098

In [74]:
#Predecimos los valores de total de accidentes a partir de la variable
y_pred= model.predict(X=df[["porc_tasa"]])
y_pred

array([3084.21150963, 3084.21150963, 3084.21150963, ..., 3080.2066795 ,
       3084.95907792, 3099.59005731])

In [75]:
#Corroboramos cual es el coeficiente de Determinación de nuestro modelo
coef_Deter=model.score(X=Vars_Indep, y=Var_Dep)
coef_Deter

0.0014077274944149787

**Modelo Matematico 8**

In [76]:
#Declaramos las variables dependientes e independientes para la regresión lineal
Vars_Indep= df[['porc_tasa']]
Var_Dep= df['porc_enganche']
#Se define model como la función de regresión lineal
from sklearn.linear_model import LinearRegression
model= LinearRegression()
#Ajustamos el modelo con las variables antes declaradas
model.fit(X=Vars_Indep, y=Var_Dep)
#Verificamos los coeficientes obtenidos para el modelo ajustado
model.__dict__

{'fit_intercept': True,
 'copy_X': True,
 'n_jobs': None,
 'positive': False,
 'feature_names_in_': array(['porc_tasa'], dtype=object),
 'n_features_in_': 1,
 'coef_': array([-0.07293431]),
 'rank_': 1,
 'singular_': array([1161.91123173]),
 'intercept_': 1.0108007593802968}

y=-0.07293431+1.0108007593802968

In [77]:
#Predecimos los valores de total de accidentes a partir de la variable
y_pred= model.predict(X=df[["porc_tasa"]])
y_pred

array([1.01080076, 1.01080076, 1.01080076, ..., 0.95610003, 1.02101156,
       1.22085157])

In [78]:
#Corroboramos cual es el coeficiente de Determinación de nuestro modelo
coef_Deter=model.score(X=Vars_Indep, y=Var_Dep)
coef_Deter

0.009570552066136218